language: java
sudo: false
install: true
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: uniqueck-github
    token:
      secure: S5WdBY2dmKD9+Rqx+31SxT+lJkiQ74mEsU3rE/T0qgU1ffWKm2NsqHygCQ3jrt39Y6N3tlkGBjVirqVITcLSVWVUh+BtTZL2nCed+eJzkoP5b/XgMiJ/fOi4gU7y11BNTHse6lED05RIM4nW736pgiW4PJzP8fNqJEC2f6M4u2BvqTpXka7ZBoBnsuOfiHaBchKT/rjOqLag3wCrDWM5mxAE3lEBqT9l/whjiwsqw2A12bNm3Wsqz+dqaF5bGyirAncL003R4ayoqzH7LogkvvlPv3wr8IpB9IJhInrL1htbJPGTix4aMQTyhmp+Ij22V9OQB4CuFwSQRReO1Mm4kGVwlEfsLq78pLqDYJCuvqbyy+JgoFm4xuyKBQdoxBCx40zTJGHm8xi8wWC1MSZJIgzeMYVT2Zx4eBnV/5N8dEozDrViRdan0MX38smyvd/WCn5OnASbcyVFynuugREGiLbQHGn4DmWwl1JKGgh2ZzY9H7eV5d5+RJeB8nfzh3xk1MtnO3Ii5RPInasOOQg496fJ2CNaxMyPP1oRocoP5nzlAEROwD8BqCeikmlQOXAUVTCvcu1J5EeRQEoba+SH3reJqAM2tMryYt6hGG9mSNoldvJS8H2tAwX9tZiRNsGCvR9JuKYkm9uIllO8/jnlFlCQ6ZkP9sCLvTdCqLRIQfg=
    branches:
    - develop
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar assembly:assembly
  -DdescriptorId=jar-with-dependencies
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
  provider: lambda
  function_name: TimBaLambda
  region: eu-west-1
  role: arn:aws:iam::470183980790:role/lambda_basic_execution
  runtime: java8
  handler_name:
  module_name: com.innolab.timba.handler.TimBaStreamHandler
  access_key_id: AKIAJME73X2UDHJDSRGQ
  secret_access_key:
    secure: Zn2xaEWPwyf3QEOCs9mKzre68CBD+LCcgBha/MJNIJyvIMJN+Ghklnx+ni/CCMU5ux1kbWmr9iRxLrghGs3LHtPFvkgGElEizlREvkX4c3S01RjvsmVbWPIu9VT2LuTvpJBNLmfJ1pK2/nK+WcxuypK1IWCwKtiGtp+ZVxSuZNPze9TmnPReC3mkAFkFm3562FU/hwi5Df3vfo2NWCpZcqh4ZEab3MrhMwvzUvCons9BmtHJJjpYWgji4rtZ2aF+0zWMQXqY4SCgjOYmXT052OYwft8E9uFcXMYawo10Pq4XNBgTiPRr1huY4aOp4hvt3aGdmDJFjaI6uyG3GtKVGoJ8UH92KihtaLBYN0GQFoDbqSbrJyzqsunIQwXNINDRWHkUZFXmFoxGgm21RkwwxbTpnp01muspH5ghe1c+7IBjJYiCx7R0Yu5Plv2AO8UWCsfQ4wEDLA3sI8Ex5eLy4PTZKWT+b9MJ15M6qFNw5UA+Lv0fXRwJVC8MEqX1JNfCTB0RidsTUn+uy2LbdH+XfCLvAb9oB61LyBJ30fgJ1GzsGdMKlkAgvO4VsEwiXDuaDiFBMeOSBjdwc+pV3PKaJHWqfK6ItaeRQh2h5YYPPCP7z6ZTg+TafWbjViikG6RFW+9aHukZQ1FLTVxbQ9B/kmtFZhJzQsB1qTwefCDttas=
